name: Automated AMM

on:
  workflow_dispatch

defaults:
  run:
    working-directory: ./AMM tests

jobs:
  AMM_TEST:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.2

      - name: Install Dependencies
        run: npm install

      - name: AMM Swap and Liquidity Scripts
        run: |
          npx hardhat run scripts/addLiquidity.js --network TESTNET
          npx hardhat run scripts/AMMSwap.js --network TESTNET
          npx hardhat run scripts/removeLiquidity.js --network TESTNET
